
abstract: Pluggable RSS/Atom Aggregator
author: Tatsuhiko Miyagawa <miyagawa@bulknews.net>
build_requires: 
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.55
license: perl
name: Plagger
no_index: 
  directory: 
    - inc
    - t
recommends: 
  Cache::FastMmap: 0
  HTML::ResolveLink: 0.02
  MIME::Lite: 0
  Net::DNS: 0
  Net::Delicious: 0
  PDF::FromHTML: 0
  POE: 0
  POE::Component::Client::DNS: 0
  POE::Component::Client::HTTP: 0
  POE::Component::IKC::Client: 0
  POE::Component::IRC: 0
  Template::Plugin::JavaScript: 0
  WWW::Mechanize: 0
  WWW::Mixi: 0
  WebService::Bloglines: 0.1
  XML::Atom: 0
  XML::Feed: 0.08
  XML::OPML: 0
  XML::RSS::LibXML: 0.16
  XML::Simple: 0
  XMLRPC::Lite: 0
  Xango: 0
requires: 
  Cache::Cache: 1.04
  Class::Accessor::Fast: 0
  DateTime: 0.29
  DateTime::Format::Mail: 0
  DateTime::Format::Strptime: 0
  DateTime::Format::W3CDTF: 0
  Digest::MD5: 0
  File::Find::Rule: 0
  HTML::Parser: 3.4
  LWP: 0
  Template: 0
  Template::Provider::Encoding: 0.04
  Text::Tags: 0
  UNIVERSAL::require: 0
  URI::Fetch: 0.04
  YAML: 0.39
  perl: 5.8.1
version: 0.5.5
